name: Continuous Integration Pipeline

on:
  workflow_dispatch:
  push:
    branches: ["*"]
  pull_request:

jobs:
  ci-validation:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker (required for building)
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run unit tests when developed

      # Build Docker image (validate it builds successfully)
      - name: Build Docker image
        run: |
          docker build -t my-app:ci-test .
